/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javagradle1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void contarElementosBasico(){
        App gestor = new App(new int[]{1,2,3,4,5});
        assertEquals(5, gestor.contar());
    }
    @Test
    public void contarElementosVacio(){
        App gestor = new App(new int[]{});
        assertEquals(0, gestor.contar());
    }
    @Test
    public void devolverPrimero(){
        App gestor = new App(new int[]{1,2,3,4,5});
        assertEquals(1, gestor.primero());
    }
    @Test
    public void devolverPrimeroVacio(){
        App gestor = new App(new int[]{});
        assertEquals(0, gestor.primero());
    }
    @Test
    public void devolverUltimo(){
        App gestor = new App(new int[]{1,2,3,4,5});
        assertEquals(5, gestor.ultimo());
    }
    @Test
    public void devolverUltimoVacio(){
        App gestor = new App(new int[]{});
        assertEquals( 0,gestor.ultimo());
    }
    @Test
    public void devolverTercero(){
        App gestor = new App(new int[]{1,2,3,4,5});
        assertEquals(3, gestor.tercero());
    }
    @Test
    public void devolverTerceroVacio(){
        App gestor = new App(new int[]{});
        assertEquals(0, gestor.tercero());
    }   
    @Test
    public void devolverTerceroMenos(){
        App gestor = new App(new int[]{1,2});
        assertEquals(0, gestor.tercero());
    }
    @Test
    public void SumarElementosBasico(){
        App gestor = new App(new int[]{1,2,3,4,5});
        assertEquals(15, gestor.sumar());
    }
    @Test
    public void SumarElementosNegativos(){
        App gestor = new App(new int[]{-5,-5,5,5});
        assertEquals(0, gestor.sumar());
    }
    @Test
    public void SumarElementosVacios(){
        App gestor = new App(new int[]{});
        assertEquals(0, gestor.sumar());
    }
    @Test
    public void MediaElementosBasicos(){
        App gestor = new App(new int[]{2,4,6,8,10});
        assertEquals(6, gestor.media());
    }
    @Test
    public void MediaElementosNegativos(){
        App gestor = new App(new int[]{-1,-4,7,10,-10});
        assertEquals(0.4, gestor.media());
    }
    @Test
    public void MediaElementosVacios(){
        App gestor = new App(new int[]{});
        assertEquals( 0, gestor.media());
    }
        
    
}
