/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javagradle1;

public class App {
    private int[] array;

    public App(int[] array){
        this.array = array;
    }
    
    public  int contar(){
        if(array != null){
            return array.length;
        }else{
            return 0;
        }
    }

    public int primero(){
        return array.length > 0 ? array[0] : 0;
    }

    public int  ultimo(){
       return array.length > 0 ? array[array.length - 1] : 0;
    }

    public  int tercero(){
        if (array.length >= 3) {
            return array[2];
        } else {
            return 0;
        }
    }

    public int sumar(){
        int suma = 0;
        for(int i = 0; i < array.length;i++){
            suma += array[i];
        }
        return suma;
        
    }
    
    public double media(){
        if(array.length == 0){
            return 0.0;
        }
        int suma = 0;
        for (int i = 0; i < array.length; i++) {
            suma += array[i];
        }
        return (double) suma / array.length;
    }
}
